# build mproxy on AppVeyor - https://ci.appveyor.com

#shallow_clone: true
clone_depth: 10
build: Script

version: '{build}'
image:
  - Visual Studio 2022

environment:
  LIBEVENT_VERSION: 2.1.12
  BOOST_ROOT: C:\Libraries\boost_1_86_0

  matrix:
    # build without shadowsocks protocol
    - ENABLE_SS: OFF
      ENABLE_HTTPS_PROXY: OFF
      USE_CRYPTO_OPENSSL: OFF
      USE_CRYPTO_MBEDTLS: OFF
      CMAKE_GENERATOR: "Visual Studio 17 2022"
      ARCH: x64
      BUILD_SUFFIX: "vc2022_x64"
      BITS: 64
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_86_0\lib64-msvc-14.3

    # build with openssl library
    - ENABLE_SS: ON
      ENABLE_HTTPS_PROXY: OFF
      USE_CRYPTO_OPENSSL: ON
      USE_CRYPTO_MBEDTLS: OFF
      CMAKE_GENERATOR: "Visual Studio 17 2022"
      ARCH: x64
      BUILD_SUFFIX: "openssl_vc2022_x64"
      BITS: 64
      OPENSSL_ROOT_DIR: C:\OpenSSL-Win64
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_86_0\lib64-msvc-14.3

    # build with mbed TLS library
    - ENABLE_SS: ON
      ENABLE_HTTPS_PROXY: OFF
      USE_CRYPTO_OPENSSL: OFF
      USE_CRYPTO_MBEDTLS: ON
      MBEDTLS_VERSION: 2.28.8
      CMAKE_GENERATOR: "Visual Studio 17 2022"
      ARCH: x64
      BUILD_SUFFIX: "mbedtls_vc2022_x64"
      BITS: 64
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_86_0\lib64-msvc-14.3

    # x86 build with mbed TLS library
    - ENABLE_SS: ON
      ENABLE_HTTPS_PROXY: OFF
      USE_CRYPTO_OPENSSL: OFF
      USE_CRYPTO_MBEDTLS: ON
      MBEDTLS_VERSION: 2.28.8
      CMAKE_GENERATOR: "Visual Studio 17 2022"
      ARCH: Win32
      BUILD_SUFFIX: "mbedtls_vc2022_x86"
      BITS: 32
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_86_0\lib32-msvc-14.3

    # build https proxy with openssl library
    #- ENABLE_SS: ON
    #  ENABLE_HTTPS_PROXY: ON
    #  USE_CRYPTO_OPENSSL: ON
    #  USE_CRYPTO_MBEDTLS: OFF

install:
- ECHO "Filesystem root:"
- ps: "ls \"C:/\""
  # recursive clone 
- git submodule update --init --recursive --depth 3
  # VC env
- if "%BITS%"=="64" (call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat") else (call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat")
  # mbedTLS
- cd \
- if defined MBEDTLS_VERSION appveyor DownloadFile https://github.com/Mbed-TLS/mbedtls/archive/v%MBEDTLS_VERSION%.tar.gz -FileName mbedtls-%MBEDTLS_VERSION%.tar.gz
- if defined MBEDTLS_VERSION 7z x mbedtls-%MBEDTLS_VERSION%.tar.gz -so | 7z x -si -ttar > nul
- if defined MBEDTLS_VERSION cd mbedtls-%MBEDTLS_VERSION%
- if defined MBEDTLS_VERSION mkdir lib
- if defined MBEDTLS_VERSION mkdir cmake-build
- if defined MBEDTLS_VERSION cd cmake-build
- if defined MBEDTLS_VERSION cmake -G "%CMAKE_GENERATOR%" -A %ARCH% ..
- if defined MBEDTLS_VERSION cmake --build . --config Release
- if defined MBEDTLS_VERSION move library\Release\*.lib ..\lib\
  # Libevent
- cd \
- appveyor DownloadFile https://github.com/libevent/libevent/releases/download/release-%LIBEVENT_VERSION%-stable/libevent-%LIBEVENT_VERSION%-stable.tar.gz
- 7z x libevent-%LIBEVENT_VERSION%-stable.tar.gz -so | 7z x -si -ttar > nul
- cd libevent-%LIBEVENT_VERSION%-stable
- nmake -f Makefile.nmake static_libs
- mkdir lib
- move *.lib lib\
- move WIN32-Code\nmake\event2\* include\event2\
- move *.h include\
- cd ..
  # 
- cd %APPVEYOR_BUILD_FOLDER%


build_script:
- mkdir cmake-build
- cd cmake-build
- cmake -G "%CMAKE_GENERATOR%" -A %ARCH% -DENABLE_HTTPS_PROXY:STRING="%ENABLE_HTTPS_PROXY%" -DENABLE_SS:STRING="%ENABLE_SS%" -DUSE_CRYPTO_OPENSSL:STRING="%USE_CRYPTO_OPENSSL%" -DUSE_CRYPTO_MBEDTLS="%USE_CRYPTO_MBEDTLS%" -DLIBEVENT_ROOT=C:\libevent-%LIBEVENT_VERSION%-stable -DMBEDTLS_ROOT_DIR=C:\mbedtls-%MBEDTLS_VERSION% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..
- cmake --build . --config Release
# TODO: 
# - cpack
# - ctest 

artifacts:
- path: cmake-build\Release
  name: mproxy_$(BUILD_SUFFIX)

deploy:
  #release: mproxy_v$(appveyor_build_version)
  #description: 'Release description'
  provider: GitHub
  auth_token:
    secure: wFxle0z6fJTg0aVgEyl46GbOPGvVb/WvnNmmO5ifTaBQx5Q3qlhlfwwIpuABfuty 
  artifact: /mproxy_.*/
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
